// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadNotes() {
  return window['go']['notes']['Note']['ReadNotes']();
}

export function Save() {
  return window['go']['notes']['Note']['Save']();
}

export function UpdateNotesBody(arg1) {
  return window['go']['notes']['Note']['UpdateNotesBody'](arg1);
}

export function UpdateNotesTitle(arg1) {
  return window['go']['notes']['Note']['UpdateNotesTitle'](arg1);
}
