// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadNotes():Promise<string>;

export function Save():Promise<void>;

export function UpdateNotesBody(arg1:string):Promise<void>;

export function UpdateNotesTitle(arg1:string):Promise<void>;
