// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDirectory(arg1:string):Promise<void>;

export function ReadNotes(arg1:string):Promise<string>;

export function RenameNotes(arg1:string,arg2:string):Promise<void>;

export function UpdateNotes(arg1:string,arg2:string):Promise<void>;
