// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDirectory(arg1) {
  return window['go']['notes']['NotesService']['ChangeDirectory'](arg1);
}

export function ReadNotes(arg1) {
  return window['go']['notes']['NotesService']['ReadNotes'](arg1);
}

export function RenameNotes(arg1, arg2) {
  return window['go']['notes']['NotesService']['RenameNotes'](arg1, arg2);
}

export function UpdateNotes(arg1, arg2) {
  return window['go']['notes']['NotesService']['UpdateNotes'](arg1, arg2);
}
