// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDebt(arg1) {
  return window['go']['debt']['DebtService']['CreateDebt'](arg1);
}

export function DeleteDebt(arg1) {
  return window['go']['debt']['DebtService']['DeleteDebt'](arg1);
}

export function GetAllDebts() {
  return window['go']['debt']['DebtService']['GetAllDebts']();
}

export function GetDebtByID(arg1) {
  return window['go']['debt']['DebtService']['GetDebtByID'](arg1);
}

export function MigrateTo(arg1) {
  return window['go']['debt']['DebtService']['MigrateTo'](arg1);
}

export function SetStore(arg1) {
  return window['go']['debt']['DebtService']['SetStore'](arg1);
}

export function UpdateDebt(arg1) {
  return window['go']['debt']['DebtService']['UpdateDebt'](arg1);
}
