// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {debt} from '../models';

export function CreateDebtItem(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function DeleteDebtItem(arg1:number):Promise<void>;

export function RetrieveDebts():Promise<Array<debt.GoBill>>;

export function UpdateDebtItem(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;
