// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDebtItem(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['debt']['Debt']['CreateDebtItem'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function DeleteDebtItem(arg1) {
  return window['go']['debt']['Debt']['DeleteDebtItem'](arg1);
}

export function RetrieveDebts() {
  return window['go']['debt']['Debt']['RetrieveDebts']();
}

export function UpdateDebtItem(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['debt']['Debt']['UpdateDebtItem'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
