// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {debt} from '../models';
import {store} from '../models';

export function CreateDebt(arg1:debt.Debt):Promise<void>;

export function DeleteDebt(arg1:number):Promise<void>;

export function GetAllDebts():Promise<Array<debt.Debt>>;

export function GetDebtByID(arg1:number):Promise<debt.Debt>;

export function MigrateTo(arg1:store.DebtStore):Promise<void>;

export function SetStore(arg1:store.DebtStore):Promise<void>;

export function UpdateDebt(arg1:debt.Debt):Promise<void>;
