// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['config']['ConfigService']['GetConfig']();
}

export function UpdateConfig(arg1) {
  return window['go']['config']['ConfigService']['UpdateConfig'](arg1);
}
