// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SwitchDebtStore(arg1, arg2, arg3) {
  return window['go']['app']['AppManager']['SwitchDebtStore'](arg1, arg2, arg3);
}
